name: build
on: 
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        java: [21]  # Current Java LTS & minimum supported by Minecraft
        os: [ubuntu-20.04, windows-2022]  # Run on both Linux and Windows
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v2  # Using v2 for better compatibility
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
        
      - name: build
        run: ./gradlew build
        
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}  # Adjusted to match the Java version used
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: Artifacts
          path: build/libs/
