name: build
permissions:
  contents: read
on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        java: [21]  # Current Java LTS & minimum supported by Minecraft
        os: [ubuntu-22.04, windows-2022]  # Updated Ubuntu to 22.04
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v4  # Updated from v2 to v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2  # Updated from v1 to v2

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4  # Updated from v2 to v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: Artifacts
          path: build/libs/